# Netlify Configuration

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Disable secrets scanning for VITE variables (they are meant to be public)
  # These are frontend environment variables that get bundled into the client code
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_PADDLE_CLIENT_TOKEN"
  
  # Node version (optional, but good to specify)
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# API proxy redirects (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://api.deffatest.online/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/paddle/*"
  to = "https://api.deffatest.online/paddle/:splat"  
  status = 200
  force = true
